import { ServerThemeProvider } from 'next-themes'
import { cn } from '@/library/utils'
import { inter, raleway } from '@/styles/fonts'
import type { Metadata } from 'next'
import '@/styles/global.sass'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = ({ children }: Props) => {
	const fonts = [inter.variable, raleway.variable]
	return (
		<ServerThemeProvider enableSystem>
			<html lang='en'>
				<body className={cn(fonts)}>{children}</body>
			</html>
		</ServerThemeProvider>
	)
}

export default RootLayout
